### ISSUE TITLE
Import Error - No module named 'normalization'

### ISSUE THREAD

**Issue by skarakulak** [RuiShu/tensorbayes#2]
Hi,

I have just discovered this git (which looks amazing:), while I was trying to make sense of the GMVAE paper.

However when I import the library, I get the following error. 

I installed the library with git bash (via pip install git+git://github.com/RuiShu/tensorbayes/)

```
import tensorbayes
Traceback (most recent call last):

  File "<ipython-input-8-dd0d1d034d2e>", line 1, in <module>
    import tensorbayes

  File "C:\ISBANK\sk68178.ISBANK\Documents\Python\Anaconda3\lib\site-packages\tensorbayes\__init__.py", line 1, in <module>
    from . import layers

  File "C:\ISBANK\sk68178.ISBANK\Documents\Python\Anaconda3\lib\site-packages\tensorbayes\layers\__init__.py", line 1, in <module>
    from .simple import *

  File "C:\ISBANK\sk68178.ISBANK\Documents\Python\Anaconda3\lib\site-packages\tensorbayes\layers\simple.py", line 3, in <module>
    from normalization import *

ImportError: No module named 'normalization'
```

**Comment by RuiShu** [comment]
Thanks for checking this library! It's still work in progress :)

Based on the error, I'm guessing you're either using python3 or enforcing explicit imports. I've made a [change](https://github.com/RuiShu/tensorbayes/commit/7baa8fe96d8b893ec21a0ac768422aeb24c3b532) that will hopefully resolve the issue.
